### ISSUE TITLE
An error occurred when parsing certain CSS code.

### ISSUE THREAD

**Issue by Ulyanov-programmer** [startracex/unnestcss#2]
While working with the plugin, part of the CSS code was successfully converted, but as it turned out, when analyzing a specific part of the code, the plugin gave an unexpected result.

### Code examples (_and the result_):
<details><summary>Successfully code (PostCSS)</summary>

**_Result: expected CSS._**

```css
section#hero {
  background: no-repeat center / cover bgImageMultiType('../../images/hero.jpg');

  display: grid();
  align-items: center;
  padding: var(--content-block-padding) var(--content-inline-padding);

  div {
    display: grid(20px);
    justify-items: start;
    backdrop-filter: blur(11px);
    background: rgba(255, 255, 255, 0.8);
    border-radius: 29px;
    padding: 50px;

    h1 {
      --text: 'Your small business <br /> growth advisors';
    }

    p {
      --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
    }

    footer {
      display: flex(10px, row wrap);

      @media (width > 426px) {
        margin-top: 20px;
      }

      button[type='button'] {
        --text: 'Our Services';
      }

      button[type='button'].white.withIcon {
        --text: '';

        img {
          --attrs: 'src="./images/notepad.svg"' 'alt=""';
          --text-after: 'Book a Meeting';
        }
      }
    }

    @media (width > 600px) {
      width: clamp(400px, 30vw, 550px);
    }

    @media (width <= 769px) {
      padding: 25px;
    }
  }
}
```

</details> 

<details><summary>Not successfully code (PostCSS)</summary>

**_Result: `' @media (width <= 769px){grid-auto-flow: column;}'`_**

```css
section#services {
  display: grid(10px);
  justify-items: center;
  background: var(--gray);
  padding: var(--content-block-padding) var(--content-inline-padding);

  header-section[centered] {
    --text: '';

    highlighted-text.green {
      --text: 'Services';
    }

    h2 {
      --text: 'Get Control Over Your Business I take your finance to next level';
      margin-bottom: 25px;
      max-width: 700px;
    }
  }

  services-container {
    width: 100%;
    display: grid(20px);
    grid-template-columns: repeat(auto-fit, minmax(280px, 3fr));

    @media (width <= 769px) {
      grid-auto-flow: column;
      /* size of the first block in this container */
      grid-template-columns: 70%;
      /* size of a block in this container */
      grid-auto-columns: 70%;
      overflow-x: scroll;
      scroll-snap-type: x mandatory;

      > * {
        scroll-snap-align: start;
      }
    }

    @media (width <= 426px) {
      grid-template-columns: 85%;
      grid-auto-columns: 85%;
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }

    service-block {
      --text: '';

      img {
        --attrs: 'src="./images/icons/stat_circle.svg"' 'alt=""';
      }

      strong {
        --text: 'Audit & Evaluation';
      }

      p {
        --text: 'Get help from Alex Moore, a professional business coach with advanced  experience on growth and business scaling.';
      }
    }
  }
}
```

</details> 

### How the plugin is used:
```js
import unNestCSS from 'unnestcss'

let code = *the code from the examples above, obtained via fs.readFileSync*
let clearCSS = unNestCSS(code, false)
```
